export const PeopleActionTypes = {
    TRY_FETCH_PEOPLE: 'TRY_FETCH_PEOPLE',
    FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
    FETCH_PEOPLE_FAIL: 'FETCH_PEOPLE_FAIL',

    LOAD_MORE_PEOPLE: 'LOAD_MORE_PEOPLE',
    LOAD_MORE_PEOPLE_SUCCESS: 'LOAD_MORE_PEOPLE_SUCCESS',
    LOAD_MORE_PEOPLE_FAIL: 'LOAD_MORE_PEOPLE_FAIL',
};
